# extract_class_data.ps1
#
# Estrae lut_ClassStartingStats (96 byte) da bank_00.dat e produce un
# annotated .asm da `incbin` o `include` in slice futuri (battle/menu).
#
# Source: bank_00.dat[$3040..$309F] = 6 classi base x 16 byte ciascuna.
# Promoted class slots (FT->KN, TH->NJ, BB->MK, RM->RW, WM->WW, BM->BW)
# sono zero a NewGame -> popolati dopo class change via codice (non in lut).
#
# Layout per classe (16 byte, padded da $B usati a $10):
#   byte $0 : class ID redundant (= class idx 0..5)
#   byte $1 : HP iniziale (1..255)
#   byte $2 : STR (strength)
#   byte $3 : AGL (agility)
#   byte $4 : INT (intelligence)
#   byte $5 : VIT (vitality)
#   byte $6 : LUCK
#   byte $7 : DMG (sub-stat: bonus damage)
#   byte $8 : HIT% (sub-stat: bonus hit rate)
#   byte $9 : EVADE (sub-stat: bonus evade rate)
#   byte $A : MDEF (magic defense)
#   byte $B..$F : unused (zero padding)
#
# Output: build/data/class_stats_7800.asm
# Usage future: incbin "data/class_stats_raw.bin" o include direttamente.

param(
    [string]$Bank00 = "$PSScriptRoot\..\FF1Disassembly-master\Final Fantasy Disassembly\bank_00.dat",
    [string]$OutDir = "$PSScriptRoot\..\build\data"
)

$ErrorActionPreference = "Stop"

# Bank 0 is loaded at $8000-$BFFF. lut_ClassStartingStats at $B040.
# Offset in bank file = $B040 - $8000 = $3040.
$OFFSET = 0x3040
$RECSIZE = 16
$NCLASSES = 6
$TOTAL = $RECSIZE * $NCLASSES   # 96 bytes

if (-not (Test-Path $OutDir)) { New-Item -ItemType Directory -Path $OutDir | Out-Null }

$bank = [System.IO.File]::ReadAllBytes($Bank00)
if ($bank.Length -lt ($OFFSET + $TOTAL)) {
    throw "bank_00.dat too small: $($bank.Length) bytes, need $($OFFSET + $TOTAL)"
}

$classNames = @('FT', 'TH', 'BB', 'RM', 'WM', 'BM')
$classFull  = @('FIGHTER', 'THIEF', 'BLACK BELT', 'RED MAGE', 'WHITE MAGE', 'BLACK MAGE')

# ---------------------------------------------------------------------------
# Console summary
# ---------------------------------------------------------------------------
Write-Host ""
Write-Host "FF1 Class Starting Stats (from bank_00.dat @ \$3040):"
Write-Host ""
Write-Host ("  {0,-2} {1,-11} HP  STR AGL INT VIT LUC | DMG HIT EVD MDF" -f "ID", "Name")
Write-Host "  -- ----------- --- --- --- --- --- --- | --- --- --- ---"
for ($c = 0; $c -lt $NCLASSES; $c++) {
    $base = $OFFSET + $c * $RECSIZE
    $id   = $bank[$base + 0]
    $hp   = $bank[$base + 1]
    $str  = $bank[$base + 2]
    $agl  = $bank[$base + 3]
    $int  = $bank[$base + 4]
    $vit  = $bank[$base + 5]
    $luck = $bank[$base + 6]
    $dmg  = $bank[$base + 7]
    $hit  = $bank[$base + 8]
    $evd  = $bank[$base + 9]
    $mdf  = $bank[$base + 10]
    Write-Host ("  {0,-2} {1,-11} {2,3} {3,3} {4,3} {5,3} {6,3} {7,3} | {8,3} {9,3} {10,3} {11,3}" `
        -f $id, $classFull[$c], $hp, $str, $agl, $int, $vit, $luck, $dmg, $hit, $evd, $mdf)
}
Write-Host ""

# ---------------------------------------------------------------------------
# Emit annotated .asm
# ---------------------------------------------------------------------------
$out = "$OutDir\class_stats_7800.asm"
$sb = New-Object System.Text.StringBuilder

[void]$sb.AppendLine('; ============================================================================')
[void]$sb.AppendLine('; FF1 Class Starting Stats  (auto-generated by tools/extract_class_data.ps1)')
[void]$sb.AppendLine(';')
[void]$sb.AppendLine('; Source: FF1Disassembly-master/bank_00.dat @ offset $3040 ($B040 in NES bank).')
[void]$sb.AppendLine('; 6 classi base (FT/TH/BB/RM/WM/BM), 16 byte ciascuna (11 usati + 5 padding).')
[void]$sb.AppendLine(';')
[void]$sb.AppendLine('; Index field (use these constants when reading from lut_ClassStartingStats):')
[void]$sb.AppendLine('; ----------------------------------------------------------------------------')
[void]$sb.AppendLine('CLS_STAT_RECSIZE  = 16')
[void]$sb.AppendLine('CLS_STAT_ID       = 0      ; redundant class id (0=FT, 1=TH, 2=BB, 3=RM, 4=WM, 5=BM)')
[void]$sb.AppendLine('CLS_STAT_HP       = 1      ; starting HP (1..255)')
[void]$sb.AppendLine('CLS_STAT_STR      = 2      ; STR base stat')
[void]$sb.AppendLine('CLS_STAT_AGL      = 3      ; AGL base stat')
[void]$sb.AppendLine('CLS_STAT_INT      = 4      ; INT base stat')
[void]$sb.AppendLine('CLS_STAT_VIT      = 5      ; VIT base stat')
[void]$sb.AppendLine('CLS_STAT_LUCK     = 6      ; LUCK base stat')
[void]$sb.AppendLine('CLS_STAT_DMG      = 7      ; sub-stat: bonus damage')
[void]$sb.AppendLine('CLS_STAT_HIT      = 8      ; sub-stat: bonus hit rate')
[void]$sb.AppendLine('CLS_STAT_EVADE    = 9      ; sub-stat: bonus evade rate')
[void]$sb.AppendLine('CLS_STAT_MDEF     = 10     ; magic defense')
[void]$sb.AppendLine('; bytes 11..15 = unused padding')
[void]$sb.AppendLine(';')
[void]$sb.AppendLine('; NewGame_LoadStartingStats (NES bank_0F.asm:1811) idiom:')
[void]$sb.AppendLine(';   LDA ch_class,X     ; class id 0..5')
[void]$sb.AppendLine(';   ASL A : ASL A : ASL A : ASL A   ; *16')
[void]$sb.AppendLine(';   TAY')
[void]$sb.AppendLine(';   LDA lut_ClassStartingStats + CLS_STAT_HP, Y')
[void]$sb.AppendLine(';   ... etc.')
[void]$sb.AppendLine(';')
[void]$sb.AppendLine('; Note: la NES award anche 2 MP iniziale ai mage (RM/WM/BM), assegnato')
[void]$sb.AppendLine('; in codice non in lut. Replicare in slice futuro.')
[void]$sb.AppendLine('; ============================================================================')
[void]$sb.AppendLine()
[void]$sb.AppendLine('lut_ClassStartingStats:')

for ($c = 0; $c -lt $NCLASSES; $c++) {
    $base = $OFFSET + $c * $RECSIZE
    $bytes = @()
    for ($i = 0; $i -lt $RECSIZE; $i++) {
        $bytes += ('${0:X2}' -f $bank[$base + $i])
    }
    $line = '    .byte ' + ($bytes -join ', ')
    [void]$sb.AppendLine(("$line ; {0} ({1})" -f $classNames[$c], $classFull[$c]))
}

[void]$sb.AppendLine()
[void]$sb.AppendLine('; Sanity decode (for grep / human reference):')
[void]$sb.AppendLine(';')
for ($c = 0; $c -lt $NCLASSES; $c++) {
    $base = $OFFSET + $c * $RECSIZE
    $line = ';   {0} {1,-10} HP={2,3}  STR={3,2} AGL={4,2} INT={5,2} VIT={6,2} LUCK={7,2}  | DMG={8,2} HIT={9,2} EVADE={10,2} MDEF={11,2}' -f `
        $classNames[$c], $classFull[$c], `
        $bank[$base+1], $bank[$base+2], $bank[$base+3], $bank[$base+4], $bank[$base+5], $bank[$base+6], `
        $bank[$base+7], $bank[$base+8], $bank[$base+9], $bank[$base+10]
    [void]$sb.AppendLine($line)
}

Set-Content -Path $out -Value $sb.ToString() -Encoding ASCII
Write-Host "Wrote $out  ($TOTAL byte data, annotated)."
Write-Host ""
