# extract_encounter_data.ps1
#
# Extract FF1 NES encounter / battle-formation data tables:
#   - OW tile attributes  (128 macros x 2 bytes)
#   - Battle domains      (128 domains x 8 formation IDs)
#   - Battle formations   (128 formations x 16 bytes; see "some formats.txt")
#   - Formation weight    (64 bytes; weighted RNG -> 0..7 index)
#   - RNG scramble LUT    (256 bytes)
#
# Sources (per Constants.inc):
#   tileset_prop          bank_00 offset 0..0xFF              (lut_OWTileset @ $8000)
#   lut_Domains           bin/0B_8000_battledomains.bin       ($8000 in BANK_DOMAINS)
#   lut_BattleFormations  bin/0B_8400_battleformations.bin    ($8400 in BANK_DOMAINS)
#   lut_FormationWeight   bank_0F.bin offset 0x58C..0x5CB     ($C58C in BANK_FIXED)
#   lut_RNG               bin/0F_F100_rngtable.bin            ($F100 in BANK_FIXED)
#
# Output:
#   src/ff1_encounter.h  - all 5 tables as C arrays

param(
    [string]$Disasm    = "$PSScriptRoot\..\FF1Disassembly-master\Final Fantasy Disassembly",
    [string]$OutHdr   = "$PSScriptRoot\..\src\ff1_encounter.h"
)

$ErrorActionPreference = 'Stop'

function ReadAll([string]$path) {
    if (-not (Test-Path $path)) { throw "Missing source: $path" }
    return [System.IO.File]::ReadAllBytes($path)
}

$bank00    = ReadAll (Join-Path $Disasm 'bank_00.dat')
$bank0F    = ReadAll (Join-Path $Disasm 'bank_0F.bin')
$domains   = ReadAll (Join-Path $Disasm 'bin\0B_8000_battledomains.bin')
$formations= ReadAll (Join-Path $Disasm 'bin\0B_8400_battleformations.bin')
$rngtable  = ReadAll (Join-Path $Disasm 'bin\0F_F100_rngtable.bin')

if ($domains.Length    -ne 1024) { throw "domains: expected 1024, got $($domains.Length)" }
if ($formations.Length -ne 2048) { throw "formations: expected 2048, got $($formations.Length)" }
if ($rngtable.Length   -ne 256)  { throw "rngtable: expected 256, got $($rngtable.Length)" }

# 256 bytes of tileset_prop = first 256 of bank_00
$attr = New-Object byte[] 256
[Array]::Copy($bank00, 0, $attr, 0, 256)

# 64 bytes of formation weight from bank_0F.bin $58C..$5CB
$fw = New-Object byte[] 64
[Array]::Copy($bank0F, 0x58C, $fw, 0, 64)

# Sanity check fw shape (should be 12 zeros, 12 ones, ..., 1 seven)
$expected = 0,0,0,0,0,0,0,0,0,0,0,0, 1,1,1,1,1,1,1,1,1,1,1,1, 2,2,2,2,2,2,2,2,2,2,2,2, 3,3,3,3,3,3,3,3,3,3,3,3, 4,4,4,4,4,4, 5,5,5,5,5,5, 6,6,6, 7
for ($i = 0; $i -lt 64; $i++) {
    if ($fw[$i] -ne $expected[$i]) { throw ("FormationWeight mismatch at {0}: got {1}, expected {2}" -f $i, $fw[$i], $expected[$i]) }
}
Write-Host "FormationWeight LUT verified."

# Generate header
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("// AUTO-GENERATED by tools/extract_encounter_data.ps1")
[void]$sb.AppendLine("// FF1 NES encounter + battle-domain tables.")
[void]$sb.AppendLine("// OW attribute byte 0 [SSdf ascw]:")
[void]$sb.AppendLine("//   SS = special (11=airship, 10=caravan, 01=chime), d=dock, f=forest,")
[void]$sb.AppendLine("//   a=no airship, s=no ship, c=no canoe, w=no walk.")
[void]$sb.AppendLine("// OW attribute byte 1:")
[void]$sb.AppendLine("//   bit 7 = teleport (low bits = teleport ID)")
[void]$sb.AppendLine("//   bit 6 = fight on this tile")
[void]$sb.AppendLine("//   sub-domain: 00=land 01/11=river 10=sea (only consulted if bit 6 set)")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("#define FF1_OW_ATTR_NOWALK   0x01")
[void]$sb.AppendLine("#define FF1_OW_ATTR_NOCANOE  0x02")
[void]$sb.AppendLine("#define FF1_OW_ATTR_NOSHIP   0x04")
[void]$sb.AppendLine("#define FF1_OW_ATTR_NOAIR    0x08")
[void]$sb.AppendLine("#define FF1_OW_ATTR_FOREST   0x10")
[void]$sb.AppendLine("#define FF1_OW_ATTR_DOCK     0x20")
[void]$sb.AppendLine("#define FF1_OW_ATTR1_TELEPORT 0x80")
[void]$sb.AppendLine("#define FF1_OW_ATTR1_FIGHT    0x40")
[void]$sb.AppendLine("#define FF1_OW_ATTR1_SUBMASK  0x03")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("// 128 OW metatiles x 2 attribute bytes")
[void]$sb.AppendLine("static const unsigned char ff1_ow_attr[128][2] = {")
for ($i = 0; $i -lt 128; $i++) {
    $line = "    {0x$($attr[$i*2].ToString('X2')), 0x$($attr[$i*2+1].ToString('X2'))}"
    if ($i -lt 127) { $line += "," } else { $line += " " }
    $line += ("  // 0x{0:X2}" -f $i)
    [void]$sb.AppendLine($line)
}
[void]$sb.AppendLine("};")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("// 128 battle domains x 8 formation IDs.")
[void]$sb.AppendLine("// Land domain index = ((y+7) & 0xE0) | (((x+7) >> 5) & 7) = 8x8 grid over 256x256 OW.")
[void]$sb.AppendLine("// Special domains: 0x40/0x41 = river, 0x42 = sea.")
[void]$sb.AppendLine("static const unsigned char ff1_domains[128][8] = {")
for ($d = 0; $d -lt 128; $d++) {
    $line = "    {"
    for ($f = 0; $f -lt 8; $f++) {
        $line += "0x{0:X2}" -f $domains[$d*8+$f]
        if ($f -lt 7) { $line += "," }
    }
    $line += "}"
    if ($d -lt 127) { $line += "," } else { $line += " " }
    $line += ("  // domain 0x{0:X2}" -f $d)
    [void]$sb.AppendLine($line)
}
[void]$sb.AppendLine("};")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("// 64 entries, weighted RNG -> 0..7 formation slot")
[void]$sb.AppendLine("static const unsigned char ff1_formation_weight[64] = {")
[void]$sb.Append("   ")
for ($i = 0; $i -lt 64; $i++) {
    [void]$sb.Append((" {0}," -f $fw[$i]))
    if (($i % 16) -eq 15 -and $i -lt 63) { [void]$sb.AppendLine(""); [void]$sb.Append("   ") }
}
[void]$sb.AppendLine("")
[void]$sb.AppendLine("};")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("// 256 bytes scrambled RNG LUT (every value 0..255 exactly once)")
[void]$sb.AppendLine("static const unsigned char ff1_rng_lut[256] = {")
for ($r = 0; $r -lt 16; $r++) {
    [void]$sb.Append("    ")
    for ($c = 0; $c -lt 16; $c++) {
        [void]$sb.Append(("0x{0:X2}" -f $rngtable[$r*16+$c]))
        if (-not ($r -eq 15 -and $c -eq 15)) { [void]$sb.Append(",") }
        if ($c -lt 15) { [void]$sb.Append(" ") }
    }
    [void]$sb.AppendLine("")
}
[void]$sb.AppendLine("};")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("// 128 battle formations x 16 bytes. See `some formats.txt` for layout.")
[void]$sb.AppendLine("// Brief: byte0 = battle_type<<4 | pattern; byte2..5 = enemy IDs;")
[void]$sb.AppendLine("// byte6..9 = formationA min/max packed (high nibble=max, low nibble=min);")
[void]$sb.AppendLine("// byteA..B = palette IDs; byteC = surprise rate; byteD = palette assign + bit0=norun;")
[void]$sb.AppendLine("// byteE..F = enemy0/1 min/max for formationB.")
[void]$sb.AppendLine("// PIATTO, non [128][16], e sotto gate: da slice55 questa tabella vive nel")
[void]$sb.AppendLine("// BANCO 12, non nella rodata della slice.")
[void]$sb.AppendLine("//   - piatto perche' sccz80 mette gli array `const` multidimensionali in")
[void]$sb.AppendLine("//     sezione DATA, e la DATA di un banco non viene mai copiata in RAM:")
[void]$sb.AppendLine("//     si leggerebbe spazzatura (bug #3 di slice44);")
[void]$sb.AppendLine("//   - sotto gate perche' i 2048 byte devono essere istanziati da UN SOLO")
[void]$sb.AppendLine("//     .c, quello del banco che li ospita.")
[void]$sb.AppendLine("// Indice: ff1_battle_formations[(id & 0x7F) * 16 + campo].")
[void]$sb.AppendLine("#ifdef FF1_FORMATIONS_DEFINE_DATA")
[void]$sb.AppendLine("const unsigned char ff1_battle_formations[128 * 16] = {")
for ($i = 0; $i -lt 128; $i++) {
    $line = "    "
    for ($j = 0; $j -lt 16; $j++) {
        $line += "0x{0:X2}" -f $formations[$i*16+$j]
        if (-not ($i -eq 127 -and $j -eq 15)) { $line += "," }
    }
    $line += ("  // formation 0x{0:X2}" -f $i)
    [void]$sb.AppendLine($line)
}
[void]$sb.AppendLine("};")
[void]$sb.AppendLine("#endif  // FF1_FORMATIONS_DEFINE_DATA")
[System.IO.File]::WriteAllText($OutHdr, $sb.ToString())
Write-Host ("Wrote {0}" -f $OutHdr)
Write-Host ("  ff1_ow_attr[128][2]              = 256 bytes")
Write-Host ("  ff1_domains[128][8]              = 1024 bytes")
Write-Host ("  ff1_formation_weight[64]         = 64 bytes")
Write-Host ("  ff1_rng_lut[256]                 = 256 bytes")
Write-Host ("  ff1_battle_formations[128][16]   = 2048 bytes")
Write-Host ("  TOTAL                            = 3648 bytes")
