# extract_ow_tilemap.ps1
#
# Extract FF1 NES overworld tilemap from bank_01_data.bin.
#
# OW format (per disassembly bank_0F.asm DecompressMap):
#   - 256 row pointers at start of bank (LE16 each), pointing into $8000-$9FFF
#   - Each row is RLE-compressed to 256 metatile IDs:
#       $00-$7F : literal metatile
#       $80-$FE : run header (tile = byte & 0x7F), next byte = run length (0 = 256)
#       $FF     : end-of-row terminator
#
# Output:
#   data/ff1_ow_full.bin            (65536 bytes raw, [y][x] -> metatile 0-127)
#   src/ff1_ow_<windowName>.h       (C header with a windowed slice)
#
# Defaults are tuned for the Coneria region around the new-game spawn point
# (OW scroll = $92, $9E from bank_00 unsram init -> player visible at $99, $A5).
#
# Usage:
#   .\extract_ow_tilemap.ps1
#   .\extract_ow_tilemap.ps1 -WindowX 122 -WindowY 134 -WindowW 64 -WindowH 64 -WindowName coneria

param(
    [string]$Disasm    = "$PSScriptRoot\..\FF1Disassembly-master\Final Fantasy Disassembly",
    [string]$OutBin    = "$PSScriptRoot\..\data\ff1_ow_full.bin",
    [string]$OutHdrDir = "$PSScriptRoot\..\src",
    [string]$WindowName = 'coneria',
    [int]$WindowX = 122,
    [int]$WindowY = 134,
    [int]$WindowW = 64,
    [int]$WindowH = 64
)

$ErrorActionPreference = 'Stop'

$dataPath = Join-Path $Disasm 'bank_01.bin'
if (-not (Test-Path $dataPath)) { throw "bank_01.bin not found at $dataPath" }
$bytes = [System.IO.File]::ReadAllBytes($dataPath)
Write-Host ("Loaded bank_01.bin ({0} bytes)" -f $bytes.Length)

# 256 row pointers, LE16, mapped to $8000..$9FFF -> file offset = ptr - 0x8000
$rowPtrs = New-Object int[] 256
for ($r = 0; $r -lt 256; $r++) {
    $lo = [int]$bytes[$r * 2]
    $hi = [int]$bytes[$r * 2 + 1]
    $rowPtrs[$r] = (($hi * 256) + $lo) - 0x8000
}

# Sanity check: all row pointers should point inside the bank file (<= 0x1FFF)
$ptrMin = [int]($rowPtrs | Measure-Object -Minimum).Minimum
$ptrMax = [int]($rowPtrs | Measure-Object -Maximum).Maximum
$ptrMinHex = '0x{0:X4}' -f $ptrMin
$ptrMaxHex = '0x{0:X4}' -f $ptrMax
Write-Host "Row pointer range: $ptrMinHex..$ptrMaxHex (file offsets)"
if ($ptrMin -lt 0x200 -or $ptrMax -ge $bytes.Length) {
    throw "Row pointer out of range: $ptrMinHex..$ptrMaxHex"
}

# RLE decode each row
$ow = New-Object 'byte[]' (256 * 256)
for ($r = 0; $r -lt 256; $r++) {
    $src = $rowPtrs[$r]
    $dst = $r * 256
    $written = 0
    while ($true) {
        if ($src -ge $bytes.Length) { throw "src overflow row $r" }
        $b = $bytes[$src]
        $src++
        if ($b -eq 0xFF) { break }
        if ($b -lt 0x80) {
            if ($written -ge 256) { throw "row $r overflow on literal" }
            $ow[$dst + $written] = $b
            $written++
        } else {
            $tile = $b -band 0x7F
            $len = $bytes[$src]
            $src++
            if ($len -eq 0) { $len = 256 }
            for ($i = 0; $i -lt $len; $i++) {
                if ($written -ge 256) { throw "row $r overflow on run (tile=$tile len=$len)" }
                $ow[$dst + $written] = $tile
                $written++
            }
        }
    }
    if ($written -ne 256) { throw "row $r decoded $written tiles (expected 256)" }
}

# Write full binary
$binDir = Split-Path $OutBin -Parent
if (-not (Test-Path $binDir)) { New-Item -ItemType Directory -Path $binDir -Force | Out-Null }
[System.IO.File]::WriteAllBytes($OutBin, $ow)
Write-Host ("Wrote {0} ({1} bytes)" -f $OutBin, $ow.Length)

# Stats on metatile usage
$histo = New-Object int[] 256
foreach ($v in $ow) { $histo[$v]++ }
$used = ($histo | Where-Object { $_ -gt 0 }).Count
$max = 0; $maxId = 0
for ($i = 0; $i -lt 256; $i++) { if ($histo[$i] -gt $max) { $max = $histo[$i]; $maxId = $i } }
Write-Host ("Unique metatiles used in full OW: {0}; most common = 0x{1:X2} ({2} tiles)" -f @($used, $maxId, $max))

# Extract window
if ($WindowX -lt 0 -or $WindowY -lt 0 -or ($WindowX + $WindowW) -gt 256 -or ($WindowY + $WindowH) -gt 256) {
    throw "Window out of OW bounds: x=$WindowX y=$WindowY w=$WindowW h=$WindowH"
}

# Compute window histogram (which metatiles appear in this region)
$winHisto = New-Object int[] 128
for ($y = 0; $y -lt $WindowH; $y++) {
    for ($x = 0; $x -lt $WindowW; $x++) {
        $m = $ow[($WindowY + $y) * 256 + ($WindowX + $x)]
        if ($m -ge 128) { throw "Unexpected metatile id 0x$($m.ToString('X2')) at ($WindowX+$x,$WindowY+$y)" }
        $winHisto[$m]++
    }
}
$winUsed = ($winHisto | Where-Object { $_ -gt 0 }).Count
Write-Host ("Window '$WindowName' ($WindowX,$WindowY ${WindowW}x${WindowH}): {0} unique metatiles" -f @($winUsed))

# Write C header for the window
$hdrPath = Join-Path $OutHdrDir ("ff1_ow_{0}.h" -f $WindowName)
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("// AUTO-GENERATED by tools/extract_ow_tilemap.ps1")
[void]$sb.AppendLine("// FF1 OW window: NES origin=($WindowX,$WindowY) size=${WindowW}x${WindowH}")
[void]$sb.AppendLine("// Source: $($dataPath -replace '\\', '/')")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("#define FF1_OW_${WindowName}_W $WindowW")
[void]$sb.AppendLine("#define FF1_OW_${WindowName}_H $WindowH")
[void]$sb.AppendLine("#define FF1_OW_${WindowName}_NES_X $WindowX")
[void]$sb.AppendLine("#define FF1_OW_${WindowName}_NES_Y $WindowY")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("static const unsigned char ff1_ow_${WindowName}[${WindowH}][${WindowW}] = {")
for ($y = 0; $y -lt $WindowH; $y++) {
    [void]$sb.Append("    {")
    for ($x = 0; $x -lt $WindowW; $x++) {
        $m = $ow[($WindowY + $y) * 256 + ($WindowX + $x)]
        [void]$sb.Append(("0x{0:X2}" -f $m))
        if ($x -lt $WindowW - 1) { [void]$sb.Append(",") }
    }
    [void]$sb.Append("}")
    if ($y -lt $WindowH - 1) { [void]$sb.Append(",") }
    [void]$sb.AppendLine(("  // y={0}" -f ($WindowY + $y)))
}
[void]$sb.AppendLine("};")
[System.IO.File]::WriteAllText($hdrPath, $sb.ToString())
Write-Host ("Wrote {0}" -f $hdrPath)
