# gen_bank_symbols.ps1
#
# Parse a z88dk .map file and emit a C header with #define ADDR for the
# symbols we care about. Used to bridge the SLICE42 main compilation with
# the SEPARATELY compiled intro_bank.c (which lives in MegaCart bank 1).
#
# The .map line format we expect (z88dk z80asm output):
#   _intro_prologue_lines = $CE80 ; addr, public, , X___src_intro_bank_c, ...
#
# Usage:
#   .\gen_bank_symbols.ps1 -Map ..\build\intro_bank.map -Out ..\src\intro_bank_symbols.h

param(
    [string]$Map = "$PSScriptRoot\..\build\intro_bank.map",
    [string]$Out = "$PSScriptRoot\..\src\intro_bank_symbols.h",
    # Prefix of symbols to extract -- we only care about the "intro_" / "gfx_"
    # / etc. ones that slice main code will dereference. The local `_sngXX_*` /
    # `_ff1_*` symbols are noise.
    [string]$Prefix = 'intro_',
    # Header guard name. Defaults to <PREFIX>BANK_SYMBOLS_H.
    [string]$Guard = ''
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path $Map)) { throw "map file not found: $Map" }

$lines = Get-Content $Map
$rx = [regex]'^_(?<name>[A-Za-z0-9_]+)\s+=\s+\$(?<hex>[0-9A-Fa-f]+)'
$found = @{}
foreach ($l in $lines) {
    $m = $rx.Match($l)
    if ($m.Success) {
        $name = $m.Groups['name'].Value
        if ($name.StartsWith($Prefix)) {
            $addr = [Convert]::ToInt32($m.Groups['hex'].Value, 16)
            $found[$name] = $addr
        }
    }
}

if ($found.Count -eq 0) { throw "no symbols with prefix '$Prefix' found in $Map" }

if ([string]::IsNullOrEmpty($Guard)) {
    $Guard = ($Prefix.TrimEnd('_').ToUpperInvariant()) + '_BANK_SYMBOLS_H'
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("// AUTO-GENERATED by tools/gen_bank_symbols.ps1")
[void]$sb.AppendLine("// Source: $Map")
[void]$sb.AppendLine("// Symbols extracted with prefix: $Prefix")
[void]$sb.AppendLine("//")
[void]$sb.AppendLine("// These addresses are valid ONLY when the corresponding MegaCart bank")
[void]$sb.AppendLine("// is currently selected for the upper window (\$C000-\$FFFF).")
[void]$sb.AppendLine("// Call mc_select_bank(N) before dereferencing.")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("#ifndef $Guard")
[void]$sb.AppendLine("#define $Guard")
[void]$sb.AppendLine("")

# Sort by address for stable output
$sorted = $found.GetEnumerator() | Sort-Object Value
foreach ($e in $sorted) {
    $upper = $e.Key.ToUpperInvariant()
    $hex = $e.Value.ToString('X4')
    [void]$sb.AppendLine("#define ${upper}_ADDR 0x${hex}")
}
[void]$sb.AppendLine("")
[void]$sb.AppendLine("#endif")

$outDir = Split-Path $Out -Parent
if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir -Force | Out-Null }
[System.IO.File]::WriteAllText($Out, $sb.ToString())
Write-Host ("Wrote {0} ({1} symbols)" -f $Out, $found.Count)
foreach ($e in $sorted) {
    $hex = $e.Value.ToString('X4')
    Write-Host ("  {0} = 0x{1}" -f $e.Key, $hex)
}
