# tools/import_ff1_data.ps1
#
# Imports FF1 game-data .asm files produced by the parallel 7800-FF
# extraction pipeline and emits Coleco-friendly C headers under src/data/.
#
# Source-of-truth: <SrcDir>/<name>_7800.asm (DASM 6502 syntax, .byte only,
# byte-pair-LE for any multi-byte values).
#
# Output: src/data/<name>.h with:
#   - #define NAME VALUE  (from "NAME = VAL" equates)
#   - static const unsigned char LABEL[] = { ... };  (from "LABEL:" + .byte rows)
#
# Re-run after the 7800 pipeline re-extracts (e.g. disasm bumped).

param(
    [string]$SrcDir = "$PSScriptRoot\..\build\data",
    [string]$OutDir = "$PSScriptRoot\..\src\data"
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path -LiteralPath $SrcDir)) {
    throw "SrcDir not found: $SrcDir"
}
if (-not (Test-Path -LiteralPath $OutDir)) {
    New-Item -ItemType Directory -Force -Path $OutDir | Out-Null
}

$srcFiles = Get-ChildItem -LiteralPath $SrcDir -Filter '*_7800.asm'
if (-not $srcFiles) {
    throw "No *_7800.asm files found under $SrcDir"
}

function Convert-DollarHex {
    param([string]$s)
    return [regex]::Replace($s, '\$([0-9A-Fa-f]+)', '0x$1')
}

foreach ($f in $srcFiles) {
    $baseName = $f.BaseName -replace '_7800$', ''
    $outFile = Join-Path $OutDir "$baseName.h"
    $guard = 'FF1_' + $baseName.ToUpper() + '_H'
    # Gate dei DATI, distinto dalla guardia di inclusione.
    #
    # Le costanti (gli offset dei campi) servono ovunque e restano sempre
    # visibili; gli ARRAY invece devono essere istanziati da UN SOLO .c, quello
    # del banco che li ospita. Senza gate, ogni file che include l'header si
    # porta dietro una copia della tabella -- e su una ROM a banchi il costo
    # non e' teorico: enemy_data e' 2560 byte.
    #
    # Era gia' cosi' in levelup_data.h, ma il gate era stato aggiunto A MANO
    # dopo la generazione: la prima rigenerazione lo avrebbe silenziosamente
    # cancellato, rompendo il banco 11. Stessa famiglia della trappola #3 di
    # [[slice44-real-root-causes]], dove un estrattore piu' vecchio del suo
    # output riportava indietro una correzione fatta a mano. Ora lo emette lo
    # script, quindi non si puo' perdere.
    $dataGate = 'FF1_' + (($baseName -replace '_data$', '').ToUpper()) + '_DEFINE_DATA'
    $gateOpen = $false

    $outLines = New-Object System.Collections.Generic.List[string]
    $outLines.Add('// AUTO-GENERATED by tools/import_ff1_data.ps1')
    $outLines.Add('// Source: build/data/' + $f.Name)
    $outLines.Add('// Do not hand-edit -- rerun import_ff1_data.ps1 to refresh.')
    $outLines.Add('')
    $outLines.Add('#ifndef ' + $guard)
    $outLines.Add('#define ' + $guard)
    $outLines.Add('')

    $inArray = $false
    $totalArrays = 0
    $totalRows = 0
    $totalConsts = 0
    $totalUnparsed = 0

    foreach ($rawLine in Get-Content -LiteralPath $f.FullName) {
        $line = $rawLine.TrimEnd("`r")

        if ($line -match '^\s*$') {
            $outLines.Add('')
            continue
        }

        # Comment line (starts with ';' possibly indented)
        if ($line -match '^\s*;(.*)$') {
            $outLines.Add('//' + $matches[1])
            continue
        }

        # Equate: NAME = VALUE  [; trailing comment]
        if ($line -match '^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*([^;]+?)\s*(;.*)?$') {
            $cName = $matches[1]
            $cVal = (Convert-DollarHex $matches[2]).Trim()
            $cTrail = ''
            if ($matches[3]) {
                $cTrail = ' // ' + (($matches[3] -replace '^;', '').Trim())
            }

            if ($inArray) {
                $outLines.Add('};')
                $outLines.Add('')
                $inArray = $false
            }

            $outLines.Add("#define $cName  $cVal$cTrail")
            $totalConsts++
            continue
        }

        # Array label: NAME: [; trailing comment]
        if ($line -match '^([A-Za-z_][A-Za-z0-9_]*):\s*(;.*)?$') {
            $lName = $matches[1]
            $lTrail = ''
            if ($matches[2]) {
                $lTrail = ' // ' + (($matches[2] -replace '^;', '').Trim())
            }

            if ($inArray) {
                $outLines.Add('};')
                $outLines.Add('')
            }

            if (-not $gateOpen) {
                $outLines.Add('#ifdef ' + $dataGate)
                $outLines.Add('')
                $gateOpen = $true
            }
            $outLines.Add("static const unsigned char ${lName}[] = {$lTrail")
            $inArray = $true
            $totalArrays++
            continue
        }

        # Data row: .byte $XX, $XX, ...  [; trailing comment]
        if ($line -match '^\s*\.byte\s+(.+?)(\s*;.*)?$') {
            $dataPart = $matches[1].Trim()
            $rowTrail = ''
            if ($matches[2]) {
                $rowTrail = '  // ' + ($matches[2].Trim().TrimStart(';').Trim())
            }
            $dataConverted = Convert-DollarHex $dataPart
            $outLines.Add("    $dataConverted,$rowTrail")
            $totalRows++
            continue
        }

        # Anything else -> preserve as comment to avoid silent loss
        $outLines.Add('// [unparsed] ' + $line)
        $totalUnparsed++
    }

    if ($inArray) {
        $outLines.Add('};')
        $outLines.Add('')
    }
    if ($gateOpen) {
        $outLines.Add('#endif // ' + $dataGate)
        $outLines.Add('')
    }

    $outLines.Add('#endif // ' + $guard)

    # PS 5.1 default = UTF-16 LE BOM. Force utf8 so z88dk reads it.
    Set-Content -LiteralPath $outFile -Value $outLines -Encoding utf8

    Write-Host ("Wrote {0,-40} arrays={1} rows={2} consts={3} unparsed={4}" -f `
        $outFile, $totalArrays, $totalRows, $totalConsts, $totalUnparsed)
}

Write-Host ''
Write-Host 'Done. Outputs in:' $OutDir
